@host = http://localhost:5265
@bearer_token = temp_token
POST {{host}}/api/abp/account/login

> ./save-token.js
###
GET http://localhost:5265/api/weatherforecast
###
GET {{host}}/api/weatherforecast
###
GET {{host}}/api/weatherforecast/secured
Authorization: Bearer {{bearer_token}}

###
GET {{host}}/api/weatherforecast

> ./test-success-status.js
###s